---
tools:
- name: "suite_snvphyl_1_2_0"
  owner: "nml"
  tool_shed_url: "https://toolshed.g2.bx.psu.edu/"
  revisions:
  - "a7094fa1d679"
  tool_panel_section_id: "irida"
  install_tool_dependencies: true
