---
tools:
- name: "suite_snvphyl_1_2_1"
  owner: "nml"
  tool_shed_url: "https://toolshed.g2.bx.psu.edu/"
  revisions:
  - "46d881dd44a8"
  tool_panel_section_id: "irida"
  install_tool_dependencies: true
