baseurl: /irida-documentation
title: IRIDA Documentation
description: Integrated Rapid Infectious Disease Analysis (IRIDA) - An open-source platform for public health genomics

github:
  repository_url: https://github.com/phac-nml/irida
